export default [
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'DRUGBANK::target::Compound:Gene',
      resource: 'DRUGBANK',
      score: 0,
      source_name: 'DrugBank:DB00328',
      source_id: 'DrugBank:DB00328',
      source_type: 'Compound',
      target_name: 'ENTREZ:5468',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'DrugBank:DB00328-DRUGBANK::target::Compound:Gene-ENTREZ:5468',
    reltype: 'DRUGBANK::target::Compound:Gene',
    source: 'Compound::DrugBank:DB00328',
    style: {
      label: {
        value: 'DRUGBANK::target::Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'GNBR::N::Compound:Gene',
      resource: 'GNBR',
      score: 0,
      source_name: 'DrugBank:DB00624',
      source_id: 'DrugBank:DB00624',
      source_type: 'Compound',
      target_name: 'ENTREZ:5468',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'DrugBank:DB00624-GNBR::N::Compound:Gene-ENTREZ:5468',
    reltype: 'GNBR::N::Compound:Gene',
    source: 'Compound::DrugBank:DB00624',
    style: {
      label: {
        value: 'GNBR::N::Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'Hetionet::CuG::Compound:Gene',
      resource: 'Hetionet',
      score: 0,
      source_name: 'DrugBank:DB00730',
      source_id: 'DrugBank:DB00730',
      source_type: 'Compound',
      target_name: 'ENTREZ:5468',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'DrugBank:DB00730-Hetionet::CuG::Compound:Gene-ENTREZ:5468',
    reltype: 'Hetionet::CuG::Compound:Gene',
    source: 'Compound::DrugBank:DB00730',
    style: {
      label: {
        value: 'Hetionet::CuG::Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'Hetionet::CbG::Compound:Gene',
      resource: 'Hetionet',
      score: 0,
      source_name: 'DrugBank:DB01250',
      source_id: 'DrugBank:DB01250',
      source_type: 'Compound',
      target_name: 'ENTREZ:5468',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'DrugBank:DB01250-Hetionet::CbG::Compound:Gene-ENTREZ:5468',
    reltype: 'Hetionet::CbG::Compound:Gene',
    source: 'Compound::DrugBank:DB01250',
    style: {
      label: {
        value: 'Hetionet::CbG::Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'GNBR::K::Compound:Gene',
      resource: 'GNBR',
      score: 0,
      source_name: 'DrugBank:DB04422',
      source_id: 'DrugBank:DB04422',
      source_type: 'Compound',
      target_name: 'ENTREZ:5468',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'DrugBank:DB04422-GNBR::K::Compound:Gene-ENTREZ:5468',
    reltype: 'GNBR::K::Compound:Gene',
    source: 'Compound::DrugBank:DB04422',
    style: {
      label: {
        value: 'GNBR::K::Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'bioarx::DrugHumGen:Compound:Gene',
      resource: 'bioarx',
      score: 0,
      source_name: 'DrugBank:DB04971',
      source_id: 'DrugBank:DB04971',
      source_type: 'Compound',
      target_name: 'ENTREZ:5468',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'DrugBank:DB04971-bioarx::DrugHumGen:Compound:Gene-ENTREZ:5468',
    reltype: 'bioarx::DrugHumGen:Compound:Gene',
    source: 'Compound::DrugBank:DB04971',
    style: {
      label: {
        value: 'bioarx::DrugHumGen:Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'DRUGBANK::target::Compound:Gene',
      resource: 'DRUGBANK',
      score: 0,
      source_name: 'DrugBank:DB05854',
      source_id: 'DrugBank:DB05854',
      source_type: 'Compound',
      target_name: 'ENTREZ:5468',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'DrugBank:DB05854-DRUGBANK::target::Compound:Gene-ENTREZ:5468',
    reltype: 'DRUGBANK::target::Compound:Gene',
    source: 'Compound::DrugBank:DB05854',
    style: {
      label: {
        value: 'DRUGBANK::target::Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'DRUGBANK::target::Compound:Gene',
      resource: 'DRUGBANK',
      score: 0,
      source_name: 'DrugBank:DB08915',
      source_id: 'DrugBank:DB08915',
      source_type: 'Compound',
      target_name: 'ENTREZ:5468',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'DrugBank:DB08915-DRUGBANK::target::Compound:Gene-ENTREZ:5468',
    reltype: 'DRUGBANK::target::Compound:Gene',
    source: 'Compound::DrugBank:DB08915',
    style: {
      label: {
        value: 'DRUGBANK::target::Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'bioarx::DrugHumGen:Compound:Gene',
      resource: 'bioarx',
      score: 0,
      source_id: 'DrugBank:DB09198',
      source_type: 'Compound',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'DrugBank:DB09198-bioarx::DrugHumGen:Compound:Gene-ENTREZ:5468',
    reltype: 'bioarx::DrugHumGen:Compound:Gene',
    source: 'Compound::DrugBank:DB09198',
    style: {
      label: {
        value: 'bioarx::DrugHumGen:Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'bioarx::DrugHumGen:Compound:Gene',
      resource: 'bioarx',
      score: 0,
      source_id: 'DrugBank:DB11811',
      source_type: 'Compound',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'DrugBank:DB11811-bioarx::DrugHumGen:Compound:Gene-ENTREZ:5468',
    reltype: 'bioarx::DrugHumGen:Compound:Gene',
    source: 'Compound::DrugBank:DB11811',
    style: {
      label: {
        value: 'bioarx::DrugHumGen:Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'STRING::REACTION::Gene:Gene',
      resource: 'STRING',
      score: 0,
      source_id: 'ENTREZ:10499',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:10499-STRING::REACTION::Gene:Gene-ENTREZ:5468',
    reltype: 'STRING::REACTION::Gene:Gene',
    source: 'Gene::ENTREZ:10499',
    style: {
      label: {
        value: 'STRING::REACTION::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'bioarx::HumGenHumGen:Gene:Gene',
      resource: 'bioarx',
      score: 0,
      source_id: 'ENTREZ:1051',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:1051-bioarx::HumGenHumGen:Gene:Gene-ENTREZ:5468',
    reltype: 'bioarx::HumGenHumGen:Gene:Gene',
    source: 'Gene::ENTREZ:1051',
    style: {
      label: {
        value: 'bioarx::HumGenHumGen:Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'GNBR::Rg::Gene:Gene',
      resource: 'GNBR',
      score: 0,
      source_id: 'ENTREZ:1387',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:1387-GNBR::Rg::Gene:Gene-ENTREZ:5468',
    reltype: 'GNBR::Rg::Gene:Gene',
    source: 'Gene::ENTREZ:1387',
    style: {
      label: {
        value: 'GNBR::Rg::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'bioarx::HumGenHumGen:Gene:Gene',
      resource: 'bioarx',
      score: 0,
      source_id: 'ENTREZ:3326',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:3326-bioarx::HumGenHumGen:Gene:Gene-ENTREZ:5468',
    reltype: 'bioarx::HumGenHumGen:Gene:Gene',
    source: 'Gene::ENTREZ:3326',
    style: {
      label: {
        value: 'bioarx::HumGenHumGen:Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'DGIDB::ANTAGONIST::Gene:Compound',
      resource: 'DGIDB',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'DrugBank:DB00586',
      target_type: 'Compound',
    },
    relid: 'ENTREZ:5468-DGIDB::ANTAGONIST::Gene:Compound-DrugBank:DB00586',
    reltype: 'DGIDB::ANTAGONIST::Gene:Compound',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'DGIDB::ANTAGONIST::Gene:Compound',
      },
    },
    target: 'Compound::DrugBank:DB00586',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'GNBR::E+::Gene:Gene',
      resource: 'GNBR',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:471',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-GNBR::E+::Gene:Gene-ENTREZ:471',
    reltype: 'GNBR::E+::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'GNBR::E+::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:471',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'GNBR::J::Gene:Disease',
      resource: 'GNBR',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'MONDO:0005053',
      target_type: 'Disease',
    },
    relid: 'ENTREZ:5468-GNBR::J::Gene:Disease-MONDO:0005053',
    reltype: 'GNBR::J::Gene:Disease',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'GNBR::J::Gene:Disease',
      },
    },
    target: 'Disease::MONDO:0005053',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'GNBR::L::Gene:Disease',
      resource: 'GNBR',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'MONDO:0009693',
      target_type: 'Disease',
    },
    relid: 'ENTREZ:5468-GNBR::L::Gene:Disease-MONDO:0009693',
    reltype: 'GNBR::L::Gene:Disease',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'GNBR::L::Gene:Disease',
      },
    },
    target: 'Disease::MONDO:0009693',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'GNBR::Q::Gene:Gene',
      resource: 'GNBR',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:2099',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-GNBR::Q::Gene:Gene-ENTREZ:2099',
    reltype: 'GNBR::Q::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'GNBR::Q::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:2099',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'GNBR::V+::Gene:Gene',
      resource: 'GNBR',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:13614',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-GNBR::V+::Gene:Gene-ENTREZ:13614',
    reltype: 'GNBR::V+::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'GNBR::V+::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:13614',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'GNBR::V+::Gene:Gene',
      resource: 'GNBR',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:3991',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-GNBR::V+::Gene:Gene-ENTREZ:3991',
    reltype: 'GNBR::V+::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'GNBR::V+::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:3991',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'Hetionet::GiG::Gene:Gene',
      resource: 'Hetionet',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:10499',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-Hetionet::GiG::Gene:Gene-ENTREZ:10499',
    reltype: 'Hetionet::GiG::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'Hetionet::GiG::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:10499',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'Hetionet::GiG::Gene:Gene',
      resource: 'Hetionet',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:8841',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-Hetionet::GiG::Gene:Gene-ENTREZ:8841',
    reltype: 'Hetionet::GiG::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'Hetionet::GiG::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:8841',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'Hetionet::GpBP::Gene:BiologicalProcess',
      resource: 'Hetionet',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'GO:0019395',
      target_type: 'BiologicalProcess',
    },
    relid: 'ENTREZ:5468-Hetionet::GpBP::Gene:BiologicalProcess-GO:0019395',
    reltype: 'Hetionet::GpBP::Gene:BiologicalProcess',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'Hetionet::GpBP::Gene:BiologicalProcess',
      },
    },
    target: 'BiologicalProcess::GO:0019395',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'Hetionet::GpBP::Gene:BiologicalProcess',
      resource: 'Hetionet',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'GO:0031669',
      target_type: 'BiologicalProcess',
    },
    relid: 'ENTREZ:5468-Hetionet::GpBP::Gene:BiologicalProcess-GO:0031669',
    reltype: 'Hetionet::GpBP::Gene:BiologicalProcess',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'Hetionet::GpBP::Gene:BiologicalProcess',
      },
    },
    target: 'BiologicalProcess::GO:0031669',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'Hetionet::GpBP::Gene:BiologicalProcess',
      resource: 'Hetionet',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'GO:0072359',
      target_type: 'BiologicalProcess',
    },
    relid: 'ENTREZ:5468-Hetionet::GpBP::Gene:BiologicalProcess-GO:0072359',
    reltype: 'Hetionet::GpBP::Gene:BiologicalProcess',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'Hetionet::GpBP::Gene:BiologicalProcess',
      },
    },
    target: 'BiologicalProcess::GO:0072359',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'Hetionet::GpMF::Gene:MolecularFunction',
      resource: 'Hetionet',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'GO:0004953',
      target_type: 'MolecularFunction',
    },
    relid: 'ENTREZ:5468-Hetionet::GpMF::Gene:MolecularFunction-GO:0004953',
    reltype: 'Hetionet::GpMF::Gene:MolecularFunction',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'Hetionet::GpMF::Gene:MolecularFunction',
      },
    },
    target: 'MolecularFunction::GO:0004953',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'Hetionet::Gr>G::Gene:Gene',
      resource: 'Hetionet',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:5927',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-Hetionet::Gr>G::Gene:Gene-ENTREZ:5927',
    reltype: 'Hetionet::Gr>G::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'Hetionet::Gr>G::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5927',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'INTACT::PHYSICAL ASSOCIATION::Gene:Gene',
      resource: 'INTACT',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:1191',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-INTACT::PHYSICAL ASSOCIATION::Gene:Gene-ENTREZ:1191',
    reltype: 'INTACT::PHYSICAL ASSOCIATION::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'INTACT::PHYSICAL ASSOCIATION::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:1191',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'STRING::ACTIVATION::Gene:Gene',
      resource: 'STRING',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:1869',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-STRING::ACTIVATION::Gene:Gene-ENTREZ:1869',
    reltype: 'STRING::ACTIVATION::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'STRING::ACTIVATION::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:1869',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'STRING::ACTIVATION::Gene:Gene',
      resource: 'STRING',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:3952',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-STRING::ACTIVATION::Gene:Gene-ENTREZ:3952',
    reltype: 'STRING::ACTIVATION::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'STRING::ACTIVATION::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:3952',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'STRING::BINDING::Gene:Gene',
      resource: 'STRING',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:85441',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-STRING::BINDING::Gene:Gene-ENTREZ:85441',
    reltype: 'STRING::BINDING::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'STRING::BINDING::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:85441',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'STRING::BINDING::Gene:Gene',
      resource: 'STRING',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:9440',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-STRING::BINDING::Gene:Gene-ENTREZ:9440',
    reltype: 'STRING::BINDING::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'STRING::BINDING::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:9440',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'STRING::OTHER::Gene:Gene',
      resource: 'STRING',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:1912',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-STRING::OTHER::Gene:Gene-ENTREZ:1912',
    reltype: 'STRING::OTHER::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'STRING::OTHER::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:1912',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'STRING::OTHER::Gene:Gene',
      resource: 'STRING',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:6015',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-STRING::OTHER::Gene:Gene-ENTREZ:6015',
    reltype: 'STRING::OTHER::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'STRING::OTHER::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:6015',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'STRING::REACTION::Gene:Gene',
      resource: 'STRING',
      score: 0,
      source_id: 'ENTREZ:5468',
      source_type: 'Gene',
      target_id: 'ENTREZ:9612',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5468-STRING::REACTION::Gene:Gene-ENTREZ:9612',
    reltype: 'STRING::REACTION::Gene:Gene',
    source: 'Gene::ENTREZ:5468',
    style: {
      label: {
        value: 'STRING::REACTION::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:9612',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'STRING::BINDING::Gene:Gene',
      resource: 'STRING',
      score: 0,
      source_id: 'ENTREZ:54797',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:54797-STRING::BINDING::Gene:Gene-ENTREZ:5468',
    reltype: 'STRING::BINDING::Gene:Gene',
    source: 'Gene::ENTREZ:54797',
    style: {
      label: {
        value: 'STRING::BINDING::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'bioarx::HumGenHumGen:Gene:Gene',
      resource: 'bioarx',
      score: 0,
      source_id: 'ENTREZ:5562',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5562-bioarx::HumGenHumGen:Gene:Gene-ENTREZ:5468',
    reltype: 'bioarx::HumGenHumGen:Gene:Gene',
    source: 'Gene::ENTREZ:5562',
    style: {
      label: {
        value: 'bioarx::HumGenHumGen:Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'STRING::OTHER::Gene:Gene',
      resource: 'STRING',
      score: 0,
      source_id: 'ENTREZ:57167',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:57167-STRING::OTHER::Gene:Gene-ENTREZ:5468',
    reltype: 'STRING::OTHER::Gene:Gene',
    source: 'Gene::ENTREZ:57167',
    style: {
      label: {
        value: 'STRING::OTHER::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'STRING::BINDING::Gene:Gene',
      resource: 'STRING',
      score: 0,
      source_id: 'ENTREZ:57492',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:57492-STRING::BINDING::Gene:Gene-ENTREZ:5468',
    reltype: 'STRING::BINDING::Gene:Gene',
    source: 'Gene::ENTREZ:57492',
    style: {
      label: {
        value: 'STRING::BINDING::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'STRING::INHIBITION::Gene:Gene',
      resource: 'STRING',
      score: 0,
      source_id: 'ENTREZ:5970',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:5970-STRING::INHIBITION::Gene:Gene-ENTREZ:5468',
    reltype: 'STRING::INHIBITION::Gene:Gene',
    source: 'Gene::ENTREZ:5970',
    style: {
      label: {
        value: 'STRING::INHIBITION::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'bioarx::HumGenHumGen:Gene:Gene',
      resource: 'bioarx',
      score: 0,
      source_id: 'ENTREZ:7791',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:7791-bioarx::HumGenHumGen:Gene:Gene-ENTREZ:5468',
    reltype: 'bioarx::HumGenHumGen:Gene:Gene',
    source: 'Gene::ENTREZ:7791',
    style: {
      label: {
        value: 'bioarx::HumGenHumGen:Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'Hetionet::Gr>G::Gene:Gene',
      resource: 'Hetionet',
      score: 0,
      source_id: 'ENTREZ:8558',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:8558-Hetionet::Gr>G::Gene:Gene-ENTREZ:5468',
    reltype: 'Hetionet::Gr>G::Gene:Gene',
    source: 'Gene::ENTREZ:8558',
    style: {
      label: {
        value: 'Hetionet::Gr>G::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'bioarx::HumGenHumGen:Gene:Gene',
      resource: 'bioarx',
      score: 0,
      source_id: 'ENTREZ:8648',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:8648-bioarx::HumGenHumGen:Gene:Gene-ENTREZ:5468',
    reltype: 'bioarx::HumGenHumGen:Gene:Gene',
    source: 'Gene::ENTREZ:8648',
    style: {
      label: {
        value: 'bioarx::HumGenHumGen:Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'Hetionet::Gr>G::Gene:Gene',
      resource: 'Hetionet',
      score: 0,
      source_id: 'ENTREZ:8837',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:8837-Hetionet::Gr>G::Gene:Gene-ENTREZ:5468',
    reltype: 'Hetionet::Gr>G::Gene:Gene',
    source: 'Gene::ENTREZ:8837',
    style: {
      label: {
        value: 'Hetionet::Gr>G::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'INTACT::DIRECT INTERACTION::Gene:Gene',
      resource: 'INTACT',
      score: 0,
      source_id: 'ENTREZ:9611',
      source_type: 'Gene',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'ENTREZ:9611-INTACT::DIRECT INTERACTION::Gene:Gene-ENTREZ:5468',
    reltype: 'INTACT::DIRECT INTERACTION::Gene:Gene',
    source: 'Gene::ENTREZ:9611',
    style: {
      label: {
        value: 'INTACT::DIRECT INTERACTION::Gene:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'GNBR::A+::Compound:Gene',
      resource: 'GNBR',
      score: 0,
      source_id: 'MESH:C513115',
      source_type: 'Compound',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'MESH:C513115-GNBR::A+::Compound:Gene-ENTREZ:5468',
    reltype: 'GNBR::A+::Compound:Gene',
    source: 'Compound::MESH:C513115',
    style: {
      label: {
        value: 'GNBR::A+::Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'GNBR::E::Compound:Gene',
      resource: 'GNBR',
      score: 0,
      source_id: 'MESH:C541580',
      source_type: 'Compound',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'MESH:C541580-GNBR::E::Compound:Gene-ENTREZ:5468',
    reltype: 'GNBR::E::Compound:Gene',
    source: 'Compound::MESH:C541580',
    style: {
      label: {
        value: 'GNBR::E::Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'GNBR::A+::Compound:Gene',
      resource: 'GNBR',
      score: 0,
      source_id: 'MESH:D012176',
      source_type: 'Compound',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'MESH:D012176-GNBR::A+::Compound:Gene-ENTREZ:5468',
    reltype: 'GNBR::A+::Compound:Gene',
    source: 'Compound::MESH:D012176',
    style: {
      label: {
        value: 'GNBR::A+::Compound:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
  {
    category: 'edge',
    data: {
      dataset: 'drkg',
      key_sentence: '',
      pmids: '',
      relation_type: 'Hetionet::DuG::Disease:Gene',
      resource: 'Hetionet',
      score: 0,
      source_id: 'MONDO:0021040',
      source_type: 'Disease',
      target_id: 'ENTREZ:5468',
      target_type: 'Gene',
    },
    relid: 'MONDO:0021040-Hetionet::DuG::Disease:Gene-ENTREZ:5468',
    reltype: 'Hetionet::DuG::Disease:Gene',
    source: 'Disease::MONDO:0021040',
    style: {
      label: {
        value: 'Hetionet::DuG::Disease:Gene',
      },
    },
    target: 'Gene::ENTREZ:5468',
  },
];
